global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['webapp:8082']
    
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']